# Generate fixed-base (generator) precomputation tables for the SEC2 curves.
#
# Run with:   sage sage/comb.sage
#
# Writes one binary table per curve to src/params/comb/<curve>.bin, each
# embedded in the library via include_bytes!. `comb_gen.py` is a dependency-free
# python equivalent that produces byte-for-byte identical files; both are
# validated by the Rust test-suite (`mul_base(k) == G * k` for every curve).
#
# Layout (per-position 4-bit window):
#
#     For each window position i in 0..windows and digit j in 1..=15:
#         table[i][j] = (j * 16^i) * G        (affine x, y)
#
#     windows = ceil(scalar_bits / 8) * 2     (two nibbles per scalar byte)
#
# The j=0 entry (point at infinity) is implicit and not stored. Each entry is
# `x || y`, big-endian over ceil(field_bits / 8) bytes; windows low-weight
# first, digits 1..15 in order. `a` is 0 for the Koblitz (k1) curves and p-3
# for the NIST (r1) curves.

import os

# (name, p, field_bits, scalar_bits, b, gx, gy)
curves = [
    ("p192k1", 2^192 - 2^32 - 2^12 - 2^8 - 2^7 - 2^6 - 2^3 - 1, 192, 192,
     3,
     0xDB4FF10EC057E9AE26B07D0280B7F4341DA5D1B1EAE06C7D,
     0x9B2F2F6D9C5628A7844163D015BE86344082AA88D95E2F9D),
    ("p192r1", 2^192 - 2^64 - 1, 192, 192,
     0x64210519E59C80E70FA7E9AB72243049FEB8DEECC146B9B1,
     0x188DA80EB03090F67CBF20EB43A18800F4FF0AFD82FF1012,
     0x07192B95FFC8DA78631011ED6B24CDD573F977A11E794811),
    ("p224k1", 2^224 - 2^32 - 2^12 - 2^11 - 2^9 - 2^7 - 2^4 - 2 - 1, 224, 225,
     5,
     0xA1455B334DF099DF30FC28A169A467E9E47075A90F7E650EB6B7A45C,
     0x7E089FED7FBA344282CAFBD6F7E319F7C0B0BD59E2CA4BDB556D61A5),
    ("p224r1", 2^224 - 2^96 + 1, 224, 224,
     0xB4050A850C04B3ABF54132565044B0B7D7BFD8BA270B39432355FFB4,
     0xB70E0CBD6BB4BF7F321390B94A03C1D356C21122343280D6115C1D21,
     0xBD376388B5F723FB4C22DFE6CD4375A05A07476444D5819985007E34),
    ("p256k1", 2^256 - 2^32 - 2^9 - 2^8 - 2^7 - 2^6 - 2^4 - 1, 256, 256,
     7,
     0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798,
     0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8),
    ("p256r1", 2^256 - 2^224 + 2^192 + 2^96 - 1, 256, 256,
     0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B,
     0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296,
     0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5),
    ("p384r1", 2^384 - 2^128 - 2^96 + 2^32 - 1, 384, 384,
     0xB3312FA7E23EE7E4988E056BE3F82D19181D9C6EFE8141120314088F5013875AC656398D8A2ED19D2A85C8EDD3EC2AEF,
     0xAA87CA22BE8B05378EB1C71EF320AD746E1D3B628BA79B9859F741E082542A385502F25DBF55296C3A545E3872760AB7,
     0x3617DE4A96262C6F5D9E98BF9292DC29F8F41DBD289A147CE9DA3113B5F0B8C00A60B1CE1D7E819D7A431D7C90EA0E5F),
    ("p521r1", 2^521 - 1, 521, 521,
     0x0051953EB9618E1C9A1F929A21A0B68540EEA2DA725B99B315F3B8B489918EF109E156193951EC7E937B1652C0BD3BB1BF073573DF883D2C34F1EF451FD46B503F00,
     0x00C6858E06B70404E9CD9E3ECB662395B4429C648139053FB521F828AF606B4D3DBAA14B5E77EFE75928FE1DC127A2FFA8DE3348B3C1856A429BF97E7E31C2E5BD66,
     0x011839296A789A3BC0045C8A5FB42C7D1BD998F54449579B446817AFBD17273E662C97EE72995EF42640C550B9013FAD0761353C7086A272C24088BE94769FD16650),
]

def gen_curve(name, p, field_bits, scalar_bits, b, gx, gy, out_dir):
    a = 0 if name.endswith("k1") else (p - 3) % p
    field_bytes = (field_bits + 7) // 8
    windows = ((scalar_bits + 7) // 8) * 2

    F = GF(p)
    E = EllipticCurve(F, [F(a), F(b)])
    G = E(gx, gy)

    def coord(n):
        return "[" + ",".join("0x%02x" % b for b in int(n).to_bytes(field_bytes, "big")) + "]"

    lines = []
    lines.append("// @generated by sage/comb.sage -- do not edit.")
    lines.append("//")
    lines.append("// Fixed-base (generator) precomputation table for %s." % name)
    lines.append("// Per-position 4-bit window: COMB_TABLE[i][j] = (j + 1) * 16^i * G as the")
    lines.append("// affine coordinates (x, y), each big-endian over %d bytes. Window i carries" % field_bytes)
    lines.append("// weight 16^i (low-weight first); j in 0..15 covers the digits 1..=15.")
    lines.append("pub const COMB_WINDOWS: usize = %d;" % windows)
    lines.append("pub static COMB_TABLE: [[([u8; %d], [u8; %d]); 15]; COMB_WINDOWS] = [" % (field_bytes, field_bytes))
    base = G  # 16^0 * G
    for _ in range(windows):
        lines.append("    [")
        acc = base  # j = 1
        for j in range(1, 16):
            if j > 1:
                acc = acc + base
            x, y = acc.xy()
            lines.append("        (%s, %s)," % (coord(x), coord(y)))
        lines.append("    ],")
        base = 16 * base
    lines.append("];")

    path = os.path.join(out_dir, "%s.rs" % name)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("%-8s field=%2dB windows=%3d -> %s" % (name, field_bytes, windows, path))

here = os.path.dirname(os.path.abspath(__file__))
out_dir = os.path.normpath(os.path.join(here, "..", "src", "params", "comb"))
os.makedirs(out_dir, exist_ok=True)
for c in curves:
    gen_curve(*c, out_dir=out_dir)
