//! ```text
//! Autogenerated: 'src/ExtractionOCaml/word_by_word_montgomery' --lang Rust --inline p112r1_scalar 64 0xdb7c2abf62e35e7628dfac6561c5 mul square add sub opp from_montgomery to_montgomery nonzero selectznz to_bytes from_bytes one msat divstep divstep_precomp
//! curve description: p112r1_scalar
//! machine_wordsize = 64 (from "64")
//! requested operations: mul, square, add, sub, opp, from_montgomery, to_montgomery, nonzero, selectznz, to_bytes, from_bytes, one, msat, divstep, divstep_precomp
//! m = 0xdb7c2abf62e35e7628dfac6561c5 (from "0xdb7c2abf62e35e7628dfac6561c5")
//!
//! NOTE: In addition to the bounds specified above each function, all
//!   functions synthesized for this Montgomery arithmetic require the
//!   input to be strictly less than the prime modulus (m), and also
//!   require the input to be in the unique saturated representation.
//!   All functions also ensure that these two properties are true of
//!   return values.
//!
//! Computed values:
//!   eval z = z[0] + (z[1] << 64)
//!   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104)
//!   twos_complement_eval z = let x1 := z[0] + (z[1] << 64) in
//!                            if x1 & (2^128-1) < 2^127 then x1 & (2^128-1) else (x1 & (2^128-1)) - 2^128
//! ```

#![allow(unused_parens)]
#![allow(non_camel_case_types)]

/// Since `Index` and `IndexMut` aren't callable in `const` contexts yet, this helper type helps unify
/// arrays and user-defined array-wrapper types into a single type which can be indexed in `const`
/// contexts. Once `const trait`s are stabilized this type can go away
struct IndexConst<T: ?Sized>(T);

impl<'a, T, const N: usize> IndexConst<&'a [T; N]> {
    #[inline(always)]
    #[allow(unused)]
    const fn index(self, i: usize) -> &'a T {
        &self.0[i]
    }
}
impl<'a, 'b, T, const N: usize> IndexConst<&'a mut &'b mut [T; N]> {
    #[inline(always)]
    #[allow(unused)]
    const fn index_mut(self, i: usize) -> &'a mut T {
        &mut self.0[i]
    }
}

/** fiat_p112r1_scalar_u1 represents values of 1 bits, stored in one byte. */
pub type fiat_p112r1_scalar_u1 = u8;
/** fiat_p112r1_scalar_i1 represents values of 1 bits, stored in one byte. */
pub type fiat_p112r1_scalar_i1 = i8;
/** fiat_p112r1_scalar_u2 represents values of 2 bits, stored in one byte. */
pub type fiat_p112r1_scalar_u2 = u8;
/** fiat_p112r1_scalar_i2 represents values of 2 bits, stored in one byte. */
pub type fiat_p112r1_scalar_i2 = i8;

/** The type fiat_p112r1_scalar_montgomery_domain_field_element is a field element in the Montgomery domain. */
/**  */
/** ```text */
/** Bounds: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]] */
/** ``` */
#[derive(Clone, Copy)]
pub struct fiat_p112r1_scalar_montgomery_domain_field_element(pub [u64; 2]);

impl core::ops::Index<usize> for fiat_p112r1_scalar_montgomery_domain_field_element {
    type Output = u64;
    #[inline]
    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl core::ops::IndexMut<usize> for fiat_p112r1_scalar_montgomery_domain_field_element {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}

impl<'a> IndexConst<&'a fiat_p112r1_scalar_montgomery_domain_field_element> {
    #[allow(unused)]
    #[inline(always)]
    const fn index(self, i: usize) -> &'a u64 {
        &self.0.0[i]
    }
}

impl<'a, 'b> IndexConst<&'a mut &'b mut fiat_p112r1_scalar_montgomery_domain_field_element> {
    #[allow(unused)]
    #[inline(always)]
    const fn index_mut(self, i: usize) -> &'a mut u64 {
        &mut self.0.0[i]
    }
}

/** The type fiat_p112r1_scalar_non_montgomery_domain_field_element is a field element NOT in the Montgomery domain. */
/**  */
/** ```text */
/** Bounds: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]] */
/** ``` */
#[derive(Clone, Copy)]
pub struct fiat_p112r1_scalar_non_montgomery_domain_field_element(pub [u64; 2]);

impl core::ops::Index<usize> for fiat_p112r1_scalar_non_montgomery_domain_field_element {
    type Output = u64;
    #[inline]
    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl core::ops::IndexMut<usize> for fiat_p112r1_scalar_non_montgomery_domain_field_element {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}

impl<'a> IndexConst<&'a fiat_p112r1_scalar_non_montgomery_domain_field_element> {
    #[allow(unused)]
    #[inline(always)]
    const fn index(self, i: usize) -> &'a u64 {
        &self.0.0[i]
    }
}

impl<'a, 'b> IndexConst<&'a mut &'b mut fiat_p112r1_scalar_non_montgomery_domain_field_element> {
    #[allow(unused)]
    #[inline(always)]
    const fn index_mut(self, i: usize) -> &'a mut u64 {
        &mut self.0.0[i]
    }
}


/// The function fiat_p112r1_scalar_addcarryx_u64 is an addition with carry.
///
/// ```text
/// Postconditions:
///   out1 = (arg1 + arg2 + arg3) mod 2^64
///   out2 = ⌊(arg1 + arg2 + arg3) / 2^64⌋
/// ```
///
/// ```text
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0xffffffffffffffff]
///   arg3: [0x0 ~> 0xffffffffffffffff]
/// ```
/// ```text
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
///   out2: [0x0 ~> 0x1]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_addcarryx_u64(out1: &mut u64, out2: &mut fiat_p112r1_scalar_u1, arg1: fiat_p112r1_scalar_u1, arg2: u64, arg3: u64) {
  let x1: u128 = (((arg1 as u128) + (arg2 as u128)) + (arg3 as u128));
  let x2: u64 = ((x1 & (0xffffffffffffffff as u128)) as u64);
  let x3: fiat_p112r1_scalar_u1 = ((x1 >> 64) as fiat_p112r1_scalar_u1);
  *out1 = x2;
  *out2 = x3;
}

/// The function fiat_p112r1_scalar_subborrowx_u64 is a subtraction with borrow.
///
/// ```text
/// Postconditions:
///   out1 = (-arg1 + arg2 + -arg3) mod 2^64
///   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^64⌋
/// ```
///
/// ```text
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0xffffffffffffffff]
///   arg3: [0x0 ~> 0xffffffffffffffff]
/// ```
/// ```text
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
///   out2: [0x0 ~> 0x1]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_subborrowx_u64(out1: &mut u64, out2: &mut fiat_p112r1_scalar_u1, arg1: fiat_p112r1_scalar_u1, arg2: u64, arg3: u64) {
  let x1: i128 = (((arg2 as i128) - (arg1 as i128)) - (arg3 as i128));
  let x2: fiat_p112r1_scalar_i1 = ((x1 >> 64) as fiat_p112r1_scalar_i1);
  let x3: u64 = ((x1 & (0xffffffffffffffff as i128)) as u64);
  *out1 = x3;
  *out2 = (((0x0 as fiat_p112r1_scalar_i2) - (x2 as fiat_p112r1_scalar_i2)) as fiat_p112r1_scalar_u1);
}

/// The function fiat_p112r1_scalar_mulx_u64 is a multiplication, returning the full double-width result.
///
/// ```text
/// Postconditions:
///   out1 = (arg1 * arg2) mod 2^64
///   out2 = ⌊arg1 * arg2 / 2^64⌋
/// ```
///
/// ```text
/// Input Bounds:
///   arg1: [0x0 ~> 0xffffffffffffffff]
///   arg2: [0x0 ~> 0xffffffffffffffff]
/// ```
/// ```text
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
///   out2: [0x0 ~> 0xffffffffffffffff]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_mulx_u64(out1: &mut u64, out2: &mut u64, arg1: u64, arg2: u64) {
  let x1: u128 = ((arg1 as u128) * (arg2 as u128));
  let x2: u64 = ((x1 & (0xffffffffffffffff as u128)) as u64);
  let x3: u64 = ((x1 >> 64) as u64);
  *out1 = x2;
  *out2 = x3;
}

/// The function fiat_p112r1_scalar_cmovznz_u64 is a single-word conditional move.
///
/// ```text
/// Postconditions:
///   out1 = (if arg1 = 0 then arg2 else arg3)
/// ```
///
/// ```text
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0xffffffffffffffff]
///   arg3: [0x0 ~> 0xffffffffffffffff]
/// ```
/// ```text
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_cmovznz_u64(out1: &mut u64, arg1: fiat_p112r1_scalar_u1, arg2: u64, arg3: u64) {
  let x1: fiat_p112r1_scalar_u1 = (!(!arg1));
  let x2: u64 = ((((((0x0 as fiat_p112r1_scalar_i2) - (x1 as fiat_p112r1_scalar_i2)) as fiat_p112r1_scalar_i1) as i128) & (0xffffffffffffffff as i128)) as u64);
  let x3: u64 = ((x2 & arg3) | ((!x2) & arg2));
  *out1 = x3;
}

/// The function fiat_p112r1_scalar_mul multiplies two field elements in the Montgomery domain.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg1 < m
///   0 ≤ eval arg2 < m
/// Postconditions:
///   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg2)) mod m
///   0 ≤ eval out1 < m
/// ```
///
#[inline]
pub const fn fiat_p112r1_scalar_mul(mut out1: &mut fiat_p112r1_scalar_montgomery_domain_field_element, arg1: &fiat_p112r1_scalar_montgomery_domain_field_element, arg2: &fiat_p112r1_scalar_montgomery_domain_field_element) {
  let x1: u64 = (*IndexConst(arg1).index(1));
  let x2: u64 = (*IndexConst(arg1).index(0));
  let mut x3: u64 = 0;
  let mut x4: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x3, &mut x4, x2, (*IndexConst(arg2).index(1)));
  let mut x5: u64 = 0;
  let mut x6: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x5, &mut x6, x2, (*IndexConst(arg2).index(0)));
  let mut x7: u64 = 0;
  let mut x8: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x7, &mut x8, 0x0, x6, x3);
  let x9: u64 = ((x8 as u64) + x4);
  let mut x10: u64 = 0;
  let mut x11: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x10, &mut x11, x5, 0x33d55a7981d08af3);
  let mut x12: u64 = 0;
  let mut x13: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x12, &mut x13, x10, 0xdb7c2abf62e3);
  let mut x14: u64 = 0;
  let mut x15: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x14, &mut x15, x10, 0x5e7628dfac6561c5);
  let mut x16: u64 = 0;
  let mut x17: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x16, &mut x17, 0x0, x15, x12);
  let x18: u64 = ((x17 as u64) + x13);
  let mut x19: u64 = 0;
  let mut x20: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x19, &mut x20, 0x0, x5, x14);
  let mut x21: u64 = 0;
  let mut x22: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x21, &mut x22, x20, x7, x16);
  let mut x23: u64 = 0;
  let mut x24: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x23, &mut x24, x22, x9, x18);
  let mut x25: u64 = 0;
  let mut x26: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x25, &mut x26, x1, (*IndexConst(arg2).index(1)));
  let mut x27: u64 = 0;
  let mut x28: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x27, &mut x28, x1, (*IndexConst(arg2).index(0)));
  let mut x29: u64 = 0;
  let mut x30: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x29, &mut x30, 0x0, x28, x25);
  let x31: u64 = ((x30 as u64) + x26);
  let mut x32: u64 = 0;
  let mut x33: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x32, &mut x33, 0x0, x21, x27);
  let mut x34: u64 = 0;
  let mut x35: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x34, &mut x35, x33, x23, x29);
  let mut x36: u64 = 0;
  let mut x37: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x36, &mut x37, x35, (x24 as u64), x31);
  let mut x38: u64 = 0;
  let mut x39: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x38, &mut x39, x32, 0x33d55a7981d08af3);
  let mut x40: u64 = 0;
  let mut x41: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x40, &mut x41, x38, 0xdb7c2abf62e3);
  let mut x42: u64 = 0;
  let mut x43: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x42, &mut x43, x38, 0x5e7628dfac6561c5);
  let mut x44: u64 = 0;
  let mut x45: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x44, &mut x45, 0x0, x43, x40);
  let x46: u64 = ((x45 as u64) + x41);
  let mut x47: u64 = 0;
  let mut x48: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x47, &mut x48, 0x0, x32, x42);
  let mut x49: u64 = 0;
  let mut x50: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x49, &mut x50, x48, x34, x44);
  let mut x51: u64 = 0;
  let mut x52: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x51, &mut x52, x50, x36, x46);
  let x53: u64 = ((x52 as u64) + (x37 as u64));
  let mut x54: u64 = 0;
  let mut x55: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x54, &mut x55, 0x0, x49, 0x5e7628dfac6561c5);
  let mut x56: u64 = 0;
  let mut x57: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x56, &mut x57, x55, x51, 0xdb7c2abf62e3);
  let mut x58: u64 = 0;
  let mut x59: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x58, &mut x59, x57, x53, (0x0 as u64));
  let mut x60: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x60, x59, x54, x49);
  let mut x61: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x61, x59, x56, x51);
  *IndexConst(&mut out1).index_mut(0) = x60;
  *IndexConst(&mut out1).index_mut(1) = x61;
}

/// The function fiat_p112r1_scalar_square squares a field element in the Montgomery domain.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg1 < m
/// Postconditions:
///   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg1)) mod m
///   0 ≤ eval out1 < m
/// ```
///
#[inline]
pub const fn fiat_p112r1_scalar_square(mut out1: &mut fiat_p112r1_scalar_montgomery_domain_field_element, arg1: &fiat_p112r1_scalar_montgomery_domain_field_element) {
  let x1: u64 = (*IndexConst(arg1).index(1));
  let x2: u64 = (*IndexConst(arg1).index(0));
  let mut x3: u64 = 0;
  let mut x4: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x3, &mut x4, x2, (*IndexConst(arg1).index(1)));
  let mut x5: u64 = 0;
  let mut x6: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x5, &mut x6, x2, (*IndexConst(arg1).index(0)));
  let mut x7: u64 = 0;
  let mut x8: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x7, &mut x8, 0x0, x6, x3);
  let x9: u64 = ((x8 as u64) + x4);
  let mut x10: u64 = 0;
  let mut x11: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x10, &mut x11, x5, 0x33d55a7981d08af3);
  let mut x12: u64 = 0;
  let mut x13: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x12, &mut x13, x10, 0xdb7c2abf62e3);
  let mut x14: u64 = 0;
  let mut x15: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x14, &mut x15, x10, 0x5e7628dfac6561c5);
  let mut x16: u64 = 0;
  let mut x17: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x16, &mut x17, 0x0, x15, x12);
  let x18: u64 = ((x17 as u64) + x13);
  let mut x19: u64 = 0;
  let mut x20: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x19, &mut x20, 0x0, x5, x14);
  let mut x21: u64 = 0;
  let mut x22: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x21, &mut x22, x20, x7, x16);
  let mut x23: u64 = 0;
  let mut x24: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x23, &mut x24, x22, x9, x18);
  let mut x25: u64 = 0;
  let mut x26: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x25, &mut x26, x1, (*IndexConst(arg1).index(1)));
  let mut x27: u64 = 0;
  let mut x28: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x27, &mut x28, x1, (*IndexConst(arg1).index(0)));
  let mut x29: u64 = 0;
  let mut x30: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x29, &mut x30, 0x0, x28, x25);
  let x31: u64 = ((x30 as u64) + x26);
  let mut x32: u64 = 0;
  let mut x33: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x32, &mut x33, 0x0, x21, x27);
  let mut x34: u64 = 0;
  let mut x35: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x34, &mut x35, x33, x23, x29);
  let mut x36: u64 = 0;
  let mut x37: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x36, &mut x37, x35, (x24 as u64), x31);
  let mut x38: u64 = 0;
  let mut x39: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x38, &mut x39, x32, 0x33d55a7981d08af3);
  let mut x40: u64 = 0;
  let mut x41: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x40, &mut x41, x38, 0xdb7c2abf62e3);
  let mut x42: u64 = 0;
  let mut x43: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x42, &mut x43, x38, 0x5e7628dfac6561c5);
  let mut x44: u64 = 0;
  let mut x45: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x44, &mut x45, 0x0, x43, x40);
  let x46: u64 = ((x45 as u64) + x41);
  let mut x47: u64 = 0;
  let mut x48: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x47, &mut x48, 0x0, x32, x42);
  let mut x49: u64 = 0;
  let mut x50: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x49, &mut x50, x48, x34, x44);
  let mut x51: u64 = 0;
  let mut x52: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x51, &mut x52, x50, x36, x46);
  let x53: u64 = ((x52 as u64) + (x37 as u64));
  let mut x54: u64 = 0;
  let mut x55: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x54, &mut x55, 0x0, x49, 0x5e7628dfac6561c5);
  let mut x56: u64 = 0;
  let mut x57: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x56, &mut x57, x55, x51, 0xdb7c2abf62e3);
  let mut x58: u64 = 0;
  let mut x59: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x58, &mut x59, x57, x53, (0x0 as u64));
  let mut x60: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x60, x59, x54, x49);
  let mut x61: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x61, x59, x56, x51);
  *IndexConst(&mut out1).index_mut(0) = x60;
  *IndexConst(&mut out1).index_mut(1) = x61;
}

/// The function fiat_p112r1_scalar_add adds two field elements in the Montgomery domain.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg1 < m
///   0 ≤ eval arg2 < m
/// Postconditions:
///   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) + eval (from_montgomery arg2)) mod m
///   0 ≤ eval out1 < m
/// ```
///
#[inline]
pub const fn fiat_p112r1_scalar_add(mut out1: &mut fiat_p112r1_scalar_montgomery_domain_field_element, arg1: &fiat_p112r1_scalar_montgomery_domain_field_element, arg2: &fiat_p112r1_scalar_montgomery_domain_field_element) {
  let mut x1: u64 = 0;
  let mut x2: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x1, &mut x2, 0x0, (*IndexConst(arg1).index(0)), (*IndexConst(arg2).index(0)));
  let mut x3: u64 = 0;
  let mut x4: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x3, &mut x4, x2, (*IndexConst(arg1).index(1)), (*IndexConst(arg2).index(1)));
  let mut x5: u64 = 0;
  let mut x6: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x5, &mut x6, 0x0, x1, 0x5e7628dfac6561c5);
  let mut x7: u64 = 0;
  let mut x8: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x7, &mut x8, x6, x3, 0xdb7c2abf62e3);
  let mut x9: u64 = 0;
  let mut x10: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x9, &mut x10, x8, (x4 as u64), (0x0 as u64));
  let mut x11: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x11, x10, x5, x1);
  let mut x12: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x12, x10, x7, x3);
  *IndexConst(&mut out1).index_mut(0) = x11;
  *IndexConst(&mut out1).index_mut(1) = x12;
}

/// The function fiat_p112r1_scalar_sub subtracts two field elements in the Montgomery domain.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg1 < m
///   0 ≤ eval arg2 < m
/// Postconditions:
///   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) - eval (from_montgomery arg2)) mod m
///   0 ≤ eval out1 < m
/// ```
///
#[inline]
pub const fn fiat_p112r1_scalar_sub(mut out1: &mut fiat_p112r1_scalar_montgomery_domain_field_element, arg1: &fiat_p112r1_scalar_montgomery_domain_field_element, arg2: &fiat_p112r1_scalar_montgomery_domain_field_element) {
  let mut x1: u64 = 0;
  let mut x2: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x1, &mut x2, 0x0, (*IndexConst(arg1).index(0)), (*IndexConst(arg2).index(0)));
  let mut x3: u64 = 0;
  let mut x4: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x3, &mut x4, x2, (*IndexConst(arg1).index(1)), (*IndexConst(arg2).index(1)));
  let mut x5: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x5, x4, (0x0 as u64), 0xffffffffffffffff);
  let mut x6: u64 = 0;
  let mut x7: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x6, &mut x7, 0x0, x1, (x5 & 0x5e7628dfac6561c5));
  let mut x8: u64 = 0;
  let mut x9: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x8, &mut x9, x7, x3, (x5 & 0xdb7c2abf62e3));
  *IndexConst(&mut out1).index_mut(0) = x6;
  *IndexConst(&mut out1).index_mut(1) = x8;
}

/// The function fiat_p112r1_scalar_opp negates a field element in the Montgomery domain.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg1 < m
/// Postconditions:
///   eval (from_montgomery out1) mod m = -eval (from_montgomery arg1) mod m
///   0 ≤ eval out1 < m
/// ```
///
#[inline]
pub const fn fiat_p112r1_scalar_opp(mut out1: &mut fiat_p112r1_scalar_montgomery_domain_field_element, arg1: &fiat_p112r1_scalar_montgomery_domain_field_element) {
  let mut x1: u64 = 0;
  let mut x2: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x1, &mut x2, 0x0, (0x0 as u64), (*IndexConst(arg1).index(0)));
  let mut x3: u64 = 0;
  let mut x4: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x3, &mut x4, x2, (0x0 as u64), (*IndexConst(arg1).index(1)));
  let mut x5: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x5, x4, (0x0 as u64), 0xffffffffffffffff);
  let mut x6: u64 = 0;
  let mut x7: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x6, &mut x7, 0x0, x1, (x5 & 0x5e7628dfac6561c5));
  let mut x8: u64 = 0;
  let mut x9: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x8, &mut x9, x7, x3, (x5 & 0xdb7c2abf62e3));
  *IndexConst(&mut out1).index_mut(0) = x6;
  *IndexConst(&mut out1).index_mut(1) = x8;
}

/// The function fiat_p112r1_scalar_from_montgomery translates a field element out of the Montgomery domain.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg1 < m
/// Postconditions:
///   eval out1 mod m = (eval arg1 * ((2^64)⁻¹ mod m)^2) mod m
///   0 ≤ eval out1 < m
/// ```
///
#[inline]
pub const fn fiat_p112r1_scalar_from_montgomery(mut out1: &mut fiat_p112r1_scalar_non_montgomery_domain_field_element, arg1: &fiat_p112r1_scalar_montgomery_domain_field_element) {
  let x1: u64 = (*IndexConst(arg1).index(0));
  let mut x2: u64 = 0;
  let mut x3: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x2, &mut x3, x1, 0x33d55a7981d08af3);
  let mut x4: u64 = 0;
  let mut x5: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x4, &mut x5, x2, 0xdb7c2abf62e3);
  let mut x6: u64 = 0;
  let mut x7: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x6, &mut x7, x2, 0x5e7628dfac6561c5);
  let mut x8: u64 = 0;
  let mut x9: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x8, &mut x9, 0x0, x7, x4);
  let mut x10: u64 = 0;
  let mut x11: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x10, &mut x11, 0x0, x1, x6);
  let mut x12: u64 = 0;
  let mut x13: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x12, &mut x13, x11, (0x0 as u64), x8);
  let mut x14: u64 = 0;
  let mut x15: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x14, &mut x15, 0x0, x12, (*IndexConst(arg1).index(1)));
  let mut x16: u64 = 0;
  let mut x17: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x16, &mut x17, x14, 0x33d55a7981d08af3);
  let mut x18: u64 = 0;
  let mut x19: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x18, &mut x19, x16, 0xdb7c2abf62e3);
  let mut x20: u64 = 0;
  let mut x21: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x20, &mut x21, x16, 0x5e7628dfac6561c5);
  let mut x22: u64 = 0;
  let mut x23: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x22, &mut x23, 0x0, x21, x18);
  let mut x24: u64 = 0;
  let mut x25: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x24, &mut x25, 0x0, x14, x20);
  let mut x26: u64 = 0;
  let mut x27: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x26, &mut x27, x25, ((x15 as u64) + ((x13 as u64) + ((x9 as u64) + x5))), x22);
  let x28: u64 = ((x27 as u64) + ((x23 as u64) + x19));
  let mut x29: u64 = 0;
  let mut x30: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x29, &mut x30, 0x0, x26, 0x5e7628dfac6561c5);
  let mut x31: u64 = 0;
  let mut x32: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x31, &mut x32, x30, x28, 0xdb7c2abf62e3);
  let mut x33: u64 = 0;
  let mut x34: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x33, &mut x34, x32, (0x0 as u64), (0x0 as u64));
  let mut x35: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x35, x34, x29, x26);
  let mut x36: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x36, x34, x31, x28);
  *IndexConst(&mut out1).index_mut(0) = x35;
  *IndexConst(&mut out1).index_mut(1) = x36;
}

/// The function fiat_p112r1_scalar_to_montgomery translates a field element into the Montgomery domain.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg1 < m
/// Postconditions:
///   eval (from_montgomery out1) mod m = eval arg1 mod m
///   0 ≤ eval out1 < m
/// ```
///
#[inline]
pub const fn fiat_p112r1_scalar_to_montgomery(mut out1: &mut fiat_p112r1_scalar_montgomery_domain_field_element, arg1: &fiat_p112r1_scalar_non_montgomery_domain_field_element) {
  let x1: u64 = (*IndexConst(arg1).index(1));
  let x2: u64 = (*IndexConst(arg1).index(0));
  let mut x3: u64 = 0;
  let mut x4: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x3, &mut x4, x2, 0xda4a43ad7f34);
  let mut x5: u64 = 0;
  let mut x6: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x5, &mut x6, x2, 0x245d42b9c948c559);
  let mut x7: u64 = 0;
  let mut x8: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x7, &mut x8, 0x0, x6, x3);
  let mut x9: u64 = 0;
  let mut x10: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x9, &mut x10, x5, 0x33d55a7981d08af3);
  let mut x11: u64 = 0;
  let mut x12: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x11, &mut x12, x9, 0xdb7c2abf62e3);
  let mut x13: u64 = 0;
  let mut x14: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x13, &mut x14, x9, 0x5e7628dfac6561c5);
  let mut x15: u64 = 0;
  let mut x16: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x15, &mut x16, 0x0, x14, x11);
  let mut x17: u64 = 0;
  let mut x18: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x17, &mut x18, 0x0, x5, x13);
  let mut x19: u64 = 0;
  let mut x20: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x19, &mut x20, x18, x7, x15);
  let mut x21: u64 = 0;
  let mut x22: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x21, &mut x22, x1, 0xda4a43ad7f34);
  let mut x23: u64 = 0;
  let mut x24: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x23, &mut x24, x1, 0x245d42b9c948c559);
  let mut x25: u64 = 0;
  let mut x26: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x25, &mut x26, 0x0, x24, x21);
  let mut x27: u64 = 0;
  let mut x28: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x27, &mut x28, 0x0, x19, x23);
  let mut x29: u64 = 0;
  let mut x30: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x29, &mut x30, x28, (((x20 as u64) + ((x8 as u64) + x4)) + ((x16 as u64) + x12)), x25);
  let mut x31: u64 = 0;
  let mut x32: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x31, &mut x32, x27, 0x33d55a7981d08af3);
  let mut x33: u64 = 0;
  let mut x34: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x33, &mut x34, x31, 0xdb7c2abf62e3);
  let mut x35: u64 = 0;
  let mut x36: u64 = 0;
  fiat_p112r1_scalar_mulx_u64(&mut x35, &mut x36, x31, 0x5e7628dfac6561c5);
  let mut x37: u64 = 0;
  let mut x38: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x37, &mut x38, 0x0, x36, x33);
  let mut x39: u64 = 0;
  let mut x40: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x39, &mut x40, 0x0, x27, x35);
  let mut x41: u64 = 0;
  let mut x42: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x41, &mut x42, x40, x29, x37);
  let x43: u64 = (((x42 as u64) + ((x30 as u64) + ((x26 as u64) + x22))) + ((x38 as u64) + x34));
  let mut x44: u64 = 0;
  let mut x45: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x44, &mut x45, 0x0, x41, 0x5e7628dfac6561c5);
  let mut x46: u64 = 0;
  let mut x47: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x46, &mut x47, x45, x43, 0xdb7c2abf62e3);
  let mut x48: u64 = 0;
  let mut x49: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x48, &mut x49, x47, (0x0 as u64), (0x0 as u64));
  let mut x50: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x50, x49, x44, x41);
  let mut x51: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x51, x49, x46, x43);
  *IndexConst(&mut out1).index_mut(0) = x50;
  *IndexConst(&mut out1).index_mut(1) = x51;
}

/// The function fiat_p112r1_scalar_nonzero outputs a single non-zero word if the input is non-zero and zero otherwise.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg1 < m
/// Postconditions:
///   out1 = 0 ↔ eval (from_montgomery arg1) mod m = 0
/// ```
///
/// ```text
/// Input Bounds:
///   arg1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
/// ```
/// ```text
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_nonzero(out1: &mut u64, arg1: &[u64; 2]) {
  let x1: u64 = ((*IndexConst(arg1).index(0)) | (*IndexConst(arg1).index(1)));
  *out1 = x1;
}

/// The function fiat_p112r1_scalar_selectznz is a multi-limb conditional select.
///
/// ```text
/// Postconditions:
///   out1 = (if arg1 = 0 then arg2 else arg3)
/// ```
///
/// ```text
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
///   arg3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
/// ```
/// ```text
/// Output Bounds:
///   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_selectznz(mut out1: &mut [u64; 2], arg1: fiat_p112r1_scalar_u1, arg2: &[u64; 2], arg3: &[u64; 2]) {
  let mut x1: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x1, arg1, (*IndexConst(arg2).index(0)), (*IndexConst(arg3).index(0)));
  let mut x2: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x2, arg1, (*IndexConst(arg2).index(1)), (*IndexConst(arg3).index(1)));
  *IndexConst(&mut out1).index_mut(0) = x1;
  *IndexConst(&mut out1).index_mut(1) = x2;
}

/// The function fiat_p112r1_scalar_to_bytes serializes a field element NOT in the Montgomery domain to bytes in little-endian order.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg1 < m
/// Postconditions:
///   out1 = map (λ x, ⌊((eval arg1 mod m) mod 2^(8 * (x + 1))) / 2^(8 * x)⌋) [0..13]
/// ```
///
/// ```text
/// Input Bounds:
///   arg1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffff]]
/// ```
/// ```text
/// Output Bounds:
///   out1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff]]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_to_bytes(mut out1: &mut [u8; 14], arg1: &[u64; 2]) {
  let x1: u64 = (*IndexConst(arg1).index(1));
  let x2: u64 = (*IndexConst(arg1).index(0));
  let x3: u8 = ((x2 & (0xff as u64)) as u8);
  let x4: u64 = (x2 >> 8);
  let x5: u8 = ((x4 & (0xff as u64)) as u8);
  let x6: u64 = (x4 >> 8);
  let x7: u8 = ((x6 & (0xff as u64)) as u8);
  let x8: u64 = (x6 >> 8);
  let x9: u8 = ((x8 & (0xff as u64)) as u8);
  let x10: u64 = (x8 >> 8);
  let x11: u8 = ((x10 & (0xff as u64)) as u8);
  let x12: u64 = (x10 >> 8);
  let x13: u8 = ((x12 & (0xff as u64)) as u8);
  let x14: u64 = (x12 >> 8);
  let x15: u8 = ((x14 & (0xff as u64)) as u8);
  let x16: u8 = ((x14 >> 8) as u8);
  let x17: u8 = ((x1 & (0xff as u64)) as u8);
  let x18: u64 = (x1 >> 8);
  let x19: u8 = ((x18 & (0xff as u64)) as u8);
  let x20: u64 = (x18 >> 8);
  let x21: u8 = ((x20 & (0xff as u64)) as u8);
  let x22: u64 = (x20 >> 8);
  let x23: u8 = ((x22 & (0xff as u64)) as u8);
  let x24: u64 = (x22 >> 8);
  let x25: u8 = ((x24 & (0xff as u64)) as u8);
  let x26: u8 = ((x24 >> 8) as u8);
  *IndexConst(&mut out1).index_mut(0) = x3;
  *IndexConst(&mut out1).index_mut(1) = x5;
  *IndexConst(&mut out1).index_mut(2) = x7;
  *IndexConst(&mut out1).index_mut(3) = x9;
  *IndexConst(&mut out1).index_mut(4) = x11;
  *IndexConst(&mut out1).index_mut(5) = x13;
  *IndexConst(&mut out1).index_mut(6) = x15;
  *IndexConst(&mut out1).index_mut(7) = x16;
  *IndexConst(&mut out1).index_mut(8) = x17;
  *IndexConst(&mut out1).index_mut(9) = x19;
  *IndexConst(&mut out1).index_mut(10) = x21;
  *IndexConst(&mut out1).index_mut(11) = x23;
  *IndexConst(&mut out1).index_mut(12) = x25;
  *IndexConst(&mut out1).index_mut(13) = x26;
}

/// The function fiat_p112r1_scalar_from_bytes deserializes a field element NOT in the Montgomery domain from bytes in little-endian order.
///
/// ```text
/// Preconditions:
///   0 ≤ bytes_eval arg1 < m
/// Postconditions:
///   eval out1 mod m = bytes_eval arg1 mod m
///   0 ≤ eval out1 < m
/// ```
///
/// ```text
/// Input Bounds:
///   arg1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff]]
/// ```
/// ```text
/// Output Bounds:
///   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffff]]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_from_bytes(mut out1: &mut [u64; 2], arg1: &[u8; 14]) {
  let x1: u64 = (((*IndexConst(arg1).index(13)) as u64) << 40);
  let x2: u64 = (((*IndexConst(arg1).index(12)) as u64) << 32);
  let x3: u64 = (((*IndexConst(arg1).index(11)) as u64) << 24);
  let x4: u64 = (((*IndexConst(arg1).index(10)) as u64) << 16);
  let x5: u64 = (((*IndexConst(arg1).index(9)) as u64) << 8);
  let x6: u8 = (*IndexConst(arg1).index(8));
  let x7: u64 = (((*IndexConst(arg1).index(7)) as u64) << 56);
  let x8: u64 = (((*IndexConst(arg1).index(6)) as u64) << 48);
  let x9: u64 = (((*IndexConst(arg1).index(5)) as u64) << 40);
  let x10: u64 = (((*IndexConst(arg1).index(4)) as u64) << 32);
  let x11: u64 = (((*IndexConst(arg1).index(3)) as u64) << 24);
  let x12: u64 = (((*IndexConst(arg1).index(2)) as u64) << 16);
  let x13: u64 = (((*IndexConst(arg1).index(1)) as u64) << 8);
  let x14: u8 = (*IndexConst(arg1).index(0));
  let x15: u64 = (x13 + (x14 as u64));
  let x16: u64 = (x12 + x15);
  let x17: u64 = (x11 + x16);
  let x18: u64 = (x10 + x17);
  let x19: u64 = (x9 + x18);
  let x20: u64 = (x8 + x19);
  let x21: u64 = (x7 + x20);
  let x22: u64 = (x5 + (x6 as u64));
  let x23: u64 = (x4 + x22);
  let x24: u64 = (x3 + x23);
  let x25: u64 = (x2 + x24);
  let x26: u64 = (x1 + x25);
  *IndexConst(&mut out1).index_mut(0) = x21;
  *IndexConst(&mut out1).index_mut(1) = x26;
}

/// The function fiat_p112r1_scalar_set_one returns the field element one in the Montgomery domain.
///
/// ```text
/// Postconditions:
///   eval (from_montgomery out1) mod m = 1 mod m
///   0 ≤ eval out1 < m
/// ```
///
#[inline]
pub const fn fiat_p112r1_scalar_set_one(mut out1: &mut fiat_p112r1_scalar_montgomery_domain_field_element) {
  *IndexConst(&mut out1).index_mut(0) = 0x1b2fae42f8c96492;
  *IndexConst(&mut out1).index_mut(1) = 0xdb7c2abf62d1;
}

/// The function fiat_p112r1_scalar_msat returns the saturated representation of the prime modulus.
///
/// ```text
/// Postconditions:
///   twos_complement_eval out1 = m
///   0 ≤ eval out1 < m
/// ```
///
/// ```text
/// Output Bounds:
///   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_msat(mut out1: &mut [u64; 3]) {
  *IndexConst(&mut out1).index_mut(0) = 0x5e7628dfac6561c5;
  *IndexConst(&mut out1).index_mut(1) = 0xdb7c2abf62e3;
  *IndexConst(&mut out1).index_mut(2) = (0x0 as u64);
}

/// The function fiat_p112r1_scalar_divstep computes a divstep.
///
/// ```text
/// Preconditions:
///   0 ≤ eval arg4 < m
///   0 ≤ eval arg5 < m
/// Postconditions:
///   out1 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then 1 - arg1 else 1 + arg1)
///   twos_complement_eval out2 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then twos_complement_eval arg3 else twos_complement_eval arg2)
///   twos_complement_eval out3 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then ⌊(twos_complement_eval arg3 - twos_complement_eval arg2) / 2⌋ else ⌊(twos_complement_eval arg3 + (twos_complement_eval arg3 mod 2) * twos_complement_eval arg2) / 2⌋)
///   eval (from_montgomery out4) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (2 * eval (from_montgomery arg5)) mod m else (2 * eval (from_montgomery arg4)) mod m)
///   eval (from_montgomery out5) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (eval (from_montgomery arg4) - eval (from_montgomery arg4)) mod m else (eval (from_montgomery arg5) + (twos_complement_eval arg3 mod 2) * eval (from_montgomery arg4)) mod m)
///   0 ≤ eval out5 < m
///   0 ≤ eval out5 < m
///   0 ≤ eval out2 < m
///   0 ≤ eval out3 < m
/// ```
///
/// ```text
/// Input Bounds:
///   arg1: [0x0 ~> 0xffffffffffffffff]
///   arg2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
///   arg3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
///   arg4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
///   arg5: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
/// ```
/// ```text
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
///   out2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
///   out3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
///   out4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
///   out5: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_divstep(out1: &mut u64, mut out2: &mut [u64; 3], mut out3: &mut [u64; 3], mut out4: &mut [u64; 2], mut out5: &mut [u64; 2], arg1: u64, arg2: &[u64; 3], arg3: &[u64; 3], arg4: &[u64; 2], arg5: &[u64; 2]) {
  let mut x1: u64 = 0;
  let mut x2: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x1, &mut x2, 0x0, (!arg1), (0x1 as u64));
  let x3: fiat_p112r1_scalar_u1 = (((x1 >> 63) as fiat_p112r1_scalar_u1) & (((*IndexConst(arg3).index(0)) & (0x1 as u64)) as fiat_p112r1_scalar_u1));
  let mut x4: u64 = 0;
  let mut x5: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x4, &mut x5, 0x0, (!arg1), (0x1 as u64));
  let mut x6: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x6, x3, arg1, x4);
  let mut x7: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x7, x3, (*IndexConst(arg2).index(0)), (*IndexConst(arg3).index(0)));
  let mut x8: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x8, x3, (*IndexConst(arg2).index(1)), (*IndexConst(arg3).index(1)));
  let mut x9: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x9, x3, (*IndexConst(arg2).index(2)), (*IndexConst(arg3).index(2)));
  let mut x10: u64 = 0;
  let mut x11: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x10, &mut x11, 0x0, (0x1 as u64), (!(*IndexConst(arg2).index(0))));
  let mut x12: u64 = 0;
  let mut x13: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x12, &mut x13, x11, (0x0 as u64), (!(*IndexConst(arg2).index(1))));
  let mut x14: u64 = 0;
  let mut x15: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x14, &mut x15, x13, (0x0 as u64), (!(*IndexConst(arg2).index(2))));
  let mut x16: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x16, x3, (*IndexConst(arg3).index(0)), x10);
  let mut x17: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x17, x3, (*IndexConst(arg3).index(1)), x12);
  let mut x18: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x18, x3, (*IndexConst(arg3).index(2)), x14);
  let mut x19: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x19, x3, (*IndexConst(arg4).index(0)), (*IndexConst(arg5).index(0)));
  let mut x20: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x20, x3, (*IndexConst(arg4).index(1)), (*IndexConst(arg5).index(1)));
  let mut x21: u64 = 0;
  let mut x22: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x21, &mut x22, 0x0, x19, x19);
  let mut x23: u64 = 0;
  let mut x24: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x23, &mut x24, x22, x20, x20);
  let mut x25: u64 = 0;
  let mut x26: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x25, &mut x26, 0x0, x21, 0x5e7628dfac6561c5);
  let mut x27: u64 = 0;
  let mut x28: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x27, &mut x28, x26, x23, 0xdb7c2abf62e3);
  let mut x29: u64 = 0;
  let mut x30: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x29, &mut x30, x28, (x24 as u64), (0x0 as u64));
  let x31: u64 = (*IndexConst(arg4).index(1));
  let x32: u64 = (*IndexConst(arg4).index(0));
  let mut x33: u64 = 0;
  let mut x34: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x33, &mut x34, 0x0, (0x0 as u64), x32);
  let mut x35: u64 = 0;
  let mut x36: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x35, &mut x36, x34, (0x0 as u64), x31);
  let mut x37: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x37, x36, (0x0 as u64), 0xffffffffffffffff);
  let mut x38: u64 = 0;
  let mut x39: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x38, &mut x39, 0x0, x33, (x37 & 0x5e7628dfac6561c5));
  let mut x40: u64 = 0;
  let mut x41: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x40, &mut x41, x39, x35, (x37 & 0xdb7c2abf62e3));
  let mut x42: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x42, x3, (*IndexConst(arg5).index(0)), x38);
  let mut x43: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x43, x3, (*IndexConst(arg5).index(1)), x40);
  let x44: fiat_p112r1_scalar_u1 = ((x16 & (0x1 as u64)) as fiat_p112r1_scalar_u1);
  let mut x45: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x45, x44, (0x0 as u64), x7);
  let mut x46: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x46, x44, (0x0 as u64), x8);
  let mut x47: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x47, x44, (0x0 as u64), x9);
  let mut x48: u64 = 0;
  let mut x49: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x48, &mut x49, 0x0, x16, x45);
  let mut x50: u64 = 0;
  let mut x51: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x50, &mut x51, x49, x17, x46);
  let mut x52: u64 = 0;
  let mut x53: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x52, &mut x53, x51, x18, x47);
  let mut x54: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x54, x44, (0x0 as u64), x19);
  let mut x55: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x55, x44, (0x0 as u64), x20);
  let mut x56: u64 = 0;
  let mut x57: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x56, &mut x57, 0x0, x42, x54);
  let mut x58: u64 = 0;
  let mut x59: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x58, &mut x59, x57, x43, x55);
  let mut x60: u64 = 0;
  let mut x61: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x60, &mut x61, 0x0, x56, 0x5e7628dfac6561c5);
  let mut x62: u64 = 0;
  let mut x63: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x62, &mut x63, x61, x58, 0xdb7c2abf62e3);
  let mut x64: u64 = 0;
  let mut x65: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_subborrowx_u64(&mut x64, &mut x65, x63, (x59 as u64), (0x0 as u64));
  let mut x66: u64 = 0;
  let mut x67: fiat_p112r1_scalar_u1 = 0;
  fiat_p112r1_scalar_addcarryx_u64(&mut x66, &mut x67, 0x0, x6, (0x1 as u64));
  let x68: u64 = ((x48 >> 1) | ((x50 << 63) & 0xffffffffffffffff));
  let x69: u64 = ((x50 >> 1) | ((x52 << 63) & 0xffffffffffffffff));
  let x70: u64 = ((x52 & 0x8000000000000000) | (x52 >> 1));
  let mut x71: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x71, x30, x25, x21);
  let mut x72: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x72, x30, x27, x23);
  let mut x73: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x73, x65, x60, x56);
  let mut x74: u64 = 0;
  fiat_p112r1_scalar_cmovznz_u64(&mut x74, x65, x62, x58);
  *out1 = x66;
  *IndexConst(&mut out2).index_mut(0) = x7;
  *IndexConst(&mut out2).index_mut(1) = x8;
  *IndexConst(&mut out2).index_mut(2) = x9;
  *IndexConst(&mut out3).index_mut(0) = x68;
  *IndexConst(&mut out3).index_mut(1) = x69;
  *IndexConst(&mut out3).index_mut(2) = x70;
  *IndexConst(&mut out4).index_mut(0) = x71;
  *IndexConst(&mut out4).index_mut(1) = x72;
  *IndexConst(&mut out5).index_mut(0) = x73;
  *IndexConst(&mut out5).index_mut(1) = x74;
}

/// The function fiat_p112r1_scalar_divstep_precomp returns the precomputed value for Bernstein-Yang-inversion (in montgomery form).
///
/// ```text
/// Postconditions:
///   eval (from_montgomery out1) = ⌊(m - 1) / 2⌋^(if ⌊log2 m⌋ + 1 < 46 then ⌊(49 * (⌊log2 m⌋ + 1) + 80) / 17⌋ else ⌊(49 * (⌊log2 m⌋ + 1) + 57) / 17⌋)
///   0 ≤ eval out1 < m
/// ```
///
/// ```text
/// Output Bounds:
///   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
/// ```
#[inline]
pub const fn fiat_p112r1_scalar_divstep_precomp(mut out1: &mut [u64; 2]) {
  *IndexConst(&mut out1).index_mut(0) = 0x5cb9335f68c089d1;
  *IndexConst(&mut out1).index_mut(1) = 0x396979811476;
}
